// 浏览器侧统一从 web-shared 取线路类型(type-only,编译期擦除,不带入 agent 运行时)。
export type {
  AgentEventFrame,
  ApiError,
  ApprovalDecision,
  ApprovalDecisionBody,
  ApprovalRequest,
  ApprovalRequestedFrame,
  ApprovalResponse,
  ApprovalScope,
  ApprovalSettledFrame,
  CreateSessionBody,
  CreateSessionResponse,
  Event,
  ListSessionsQuery,
  ListSessionsResponse,
  PermissionMode,
  PromptBody,
  QuestionAnswerBody,
  QuestionAnswers,
  QuestionItem,
  QuestionOption,
  QuestionRequest,
  QuestionRequestedFrame,
  QuestionResult,
  QuestionSettledFrame,
  ServerFrame,
  SessionStatus,
  SessionStatusResponse,
  SessionSummary,
  SetPermissionBody,
  SteerBody,
  SysConnectedFrame,
  SysErrorFrame,
  SysHeartbeatFrame,
  ToolInputDisplay,
} from '@byfriends/web-shared';
